### ISSUE TITLE
Accessing PHPMyAdmin

### ISSUE THREAD

**Issue by leonardbos** [coloso/symfony-docker#14]
How do I access PHPmyAdmin. What address and port should I use?

**Comment by coloso** [comment]
i need more input here. You can use every free port. 8082?
Post your docker-compose.yml next time

**Comment by leonardbos** [comment]
I am using the docker-compose file specified in the repository, but when I run this configuration I and navigate to "192.168.2.4" with port "8183" I don't get the PhpMyAdmin interface in my browser.

Symfony however is working perfectly fine on the localhost. 

I am a beginner in Docker but I don't understand why PhpMyAdmin is not working when I navigate to the specified address with the right port. Am I missing something here?

My docker-compose.yml:

```
version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: project_mysql
    networks:
      default:
        ipv4_address: 192.168.2.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      default:
        ipv4_address: 192.168.2.4
    ports:
      - 8183:80

  web:
    build: ./.docker
    container_name: project_web
    networks:
      default:
        ipv4_address: 192.168.2.2
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:8080"
    depends_on:
      - "mysql"

  mailhog:
    image: mailhog/mailhog
    container_name: project_mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      default:
        ipv4_address: 192.168.2.5

  develop_init:
    build: ./.docker
    container_name: project_develop_init
    volumes:
      - ./:/var/www/html/
      - ./.docker/develop_init.sh:/usr/local/bin/develop_init
    depends_on:
      - "mysql"
      - "web"
    command: "develop_init"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24 # If you change this, make sure to change other IP addresses

```
