### ISSUE TITLE
PDO::__construct(): The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by abssimon** [coloso/symfony-docker#5]
a few minor things

connection to mysql 8 dont work
```

In AbstractMySQLDriver.php line 106:
                                                                                                                            
  An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client  
                                                                                                                            

In PDOConnection.php line 31:
                                                                                           
  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client  
                                                                                           

In PDOConnection.php line 27:
                                                                                           
  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client  
                                                                                           

In PDOConnection.php line 27:
                                                                                                                
  PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]  
                                                    
```                                                            
I step back to this
```

version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
...
```
Have seen this here https://github.com/joeymasip/docker-symfony4/issues/1

this command did not stop
`docker-compose up --build  `
(I need to press Strg C for exit) maybe -d is also an option

after installation I need to chown these "root folder"
```
~/Development/symfony-docker$ sudo chown -R $USER logs
~/Development/symfony-docker$ sudo chown -R $USER symfony
```
thanks for this build ;)
