### ISSUE TITLE
Development - Symfony do not recognize changes

### ISSUE THREAD

**Issue by abssimon** [coloso/symfony-docker#7]
Hello,

when I change the local symfony/.env file - "APP_ENV" to "prod",
the web debug toolbar disappears. 

All other local changes (not inside the container) 
under "src" are without effect, unless I remove my 
local symfony/var/cache/dev folder.

I try to disable opcache "opcache.enable=0" in docker/php/php.ini,
and restart the container (docker-compose down & docker-compose up -d)
but opcache is still enabled (http://localhost/_profiler/phpinfo > Opcode Caching - Up and Running)

Thank you & Best Regards
Simon

**Comment by coloso** [comment]
Hello Simon, first this ist not a issue that belongs here.

Read the docs about your Symfony issues: https://symfony.com/doc/current/deployment.html

The webprofiler disappears when symfony uses the prod environment.
And opcache is not equated with caching.

**Comment by abssimon** [comment]
I fixed it ;) 

changing  "opcache.validate_timestamps=1" in docker/php/php.ini and running "docker-compose up --build -d" once. Maybe this is something for the README.md. 

My docker-compose.yml currently looks like this

```
version: '3.7'
services:

    mysql:
        image: mysql:5.7
        ports: ['3306:3306']
        environment:
            - MYSQL_ROOT_PASSWORD=t9gwVoAiZLzSC2ty3Sm2GS2oJmcLmSka
            - MYSQL_DATABASE=symfony
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=CpiASvhs88mW74x2DiaSxL35zdWxi3pM
        volumes:
            - ./var/mysql:/var/lib/mysql

    php:
        build: ./docker/php
        ports: ['9000:9001']
        links:
            - mysql
        volumes:
            - ./symfony/:/var/www/symfony:cached

    nginx:
        build: ./docker/nginx
        ports: ['80:80']
        links:
            - php
        volumes:
            - ./var/nginx:/var/log/nginx:cached
            - ./symfony/:/var/www/symfony:cached
```
I think when you have an existing project with database content, you really need 
that the database persists.

Best Regards
Simon
