### ISSUE TITLE
No directory mapping on Windows 7

### ISSUE THREAD

**Issue by DominikStyp** [coloso/symfony-docker#8]
Hello I have the following issue: When i run everything exactly with this tutorial, my container works. I go to the http://192.168.99.100/ and i see Symfony 4.3.2 welcome screen, no errors.
But problem is that i don't have any directory mappings, so i go to my symfony-docker directory where I see: docker-compose.yml, docker directory, and other files BUT no symfony directory to be found. Seems like following mapping does not work:
```yaml
volumes:
      - ./symfony/:/var/www/symfony:cached
```
What would be cause of this ?
I have all the files inside the container but no mapping outside.
I've tried many things like removing **:cached** parameter, and rebuilding container.
None of it works. My docker-compose.yml is:
```yaml
version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - mysql
    volumes:
      - ./symfony/:/var/www/symfony
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony/:/var/www/symfony
```
